cloudoperators/greenhouse-extensions

- kubeconfig-generator/chart/Chart.yaml
- kubeconfig-generator/chart/templates/clusterrolebinding.yaml
- kubeconfig-generator/chart/templates/configmap.yaml
- kubeconfig-generator/plugin.yaml
I have renamed the _ClusterRoleBinding_ to ensure no name-clashes if the _Plugin_ is deployed by different organizations.
The registry was changed to have the upload work with the existing CI piplines to upload the chart to our OCI registry.
> fix(kubecfg-gen): map CRoleBinding to CRole, change registry

- kubeconfig-generator/chart/Chart.yaml
- kubeconfig-generator/chart/templates/configmap.yaml
- kubeconfig-generator/plugin.yaml
Controller does not parse Config if the `.cluster.name` is _*_  and not quoted.
> fix(kubecfg-gen): quote cluster.name, typo for clientSecretRef

- .github/CODEOWNERS
Fix typo in dir name `/exposed-service/` -> `/exposed-services/`
> fix(codeowners) typo in codeowners file

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/values.yaml
current settings did not allow prometheus to write files. the folder was created correctly under /data but it then failed with missing write permissions
I am happy to start the discussion, whether there is a better way here or not, this however is working, the old settings weren't.
> fix: security context to allow disk writes

- alerts/ui/package-lock.json
- alerts/ui/package.json
- Set the MFE public
- Remove stars from the peerDependencies
- Set some peerDependencies version equal to the devDependencies
- Fixes some typos appProps description
- Patch version upgrade
> fix(alerts-ui): make app public, remove stars from peerDependencies and some typos

- heureka/ui/package-lock.json
- heureka/ui/package.json
- heureka/ui/src/App.js
- heureka/ui/src/actions.js
- Add error boundry codeblock to the app.js
- Extend fetchFromAPI func to cover the errors which occur in graphql api.
- Remove react-query pkg from peerDependencies to solve the following error loading heureka with black screen in greenhouse dashboard:
`es-module-shims.js:780 Uncaught (in promise) Error: Unsupported Content-Type "application/octet-stream" loading https://assets.juno.qa-de-1.cloud.sap/externals/@tanstack/react-query@5.36.2/build/legacy/index.cjs imported from https://assets.juno.qa-de-1.cloud.sap/apps/heureka@latest/build/App-AOJYYGXT.js. Modules must be served with a valid MIME type like application/javascript.
at fetchModule (es-module-shims.js:780:13)
at async es-module-shims.js:825:40`
> fix(heureka) : Add error boundry to the app

- opentelemetry-collector/chart/Chart.yaml
As the owner-info is currently mandatory for deploying via CI pipeline this is a temporary fix. Will be redacted soon.
> [opentelemetry-operator] temp add owner-info for pipeline

- .github/CODEOWNERS
* Replace lists of individual contributors with teams as applicable
* change owner of `/workflows/` folder to core team so that more people can approve PRs
> feat(codeowners): Replace lists of individuals with teams where appropriate

- exposed-services/README.md
add documentation of how to specify a named port to be exposed.
To be merged after https://github.com/cloudoperators/greenhouse/pull/308
None
Knowledge of how to specify a named port to be exposed
> docs: exposing named ports

- .github/CODEOWNERS
Update Codeowners file after changing repository from /opentelemetry-collector to /opentelemetry-operator.
> [CODEOWNERS] change name for otel repo

- kube-monitoring/plugin.yaml
we don't want to use prometheus-operated to be able to operate more than one prometheus by namespace specced with thanos
> chore(thanos): enable dedicated ingress for thanos sidecar

- kube-monitoring/plugin.yaml
thanosIngress injects more than needed and we only want the additional grpc port exposed to map prometheus directly. 
This fixes the non functional plugin due to mission thanosIngress options.
Always having this port doesn't hurt, so default is the way to go here.
> fix(thanos): no thanosIngress and dedicated port mapping

- .github/CODEOWNERS
Adding one additional person to the greenhouse-extensions/opentelemetry-operator repository.
> [CODEOWNERS] add ivo to OTel repository

- opentelemetry-operator/chart/values.yaml
Currently the collectors image (+tag) is provided through the PluginDefinition. When checking for the image via`kubectl otelcol` the image is missing. This is a attempt to check if hard-wiring the image will fix the issue. Test worked in test env.
> [opentelemetry-operator] hard-wire collector image

- opentelemetry-operator/chart/Chart.yaml
- opentelemetry-operator/chart/templates/logs-collector.yaml
- opentelemetry-operator/chart/templates/metrics-collector.yaml
Currently the Operator does not automatically start the Custome Resources (CRs) from the Collector. This should fix it.
> [opentelemetry-operator] add mode deployment, bump version

- opentelemetry-operator/chart/Chart.yaml
- opentelemetry-operator/chart/crds/crd-opentelemetrycollector.yaml
- opentelemetry-operator/plugindefinition.yaml
Currently the deployment runs into `failed to create resource: Internal error occurred: Internal error occurred: conversion webhook for opentelemetry.io/v1alpha1`. This PR includes the missing webhook configuration for the CRD resource.
> [opentelemetry-operator] add webhook config to crd

- .github/licenserc.yaml
- .github/workflows/integration-test-build-publish.yaml
- Dockerfile.integration-test
This pull request adds a new workflow for building and publishing an integration test Docker image. The workflow is triggered when there is a change in `Docker.integration-test` file and when a tag matching the pattern "v*.*.*" is pushed. It builds the Docker image using the Dockerfile.integration-test file and pushes it to the registry. Additionally, a vulnerability scan step is included to scan the image for vulnerabilities using Trivy and upload the scan results to the GHAS. 
I have already tested this workflow in my [personal github repository](https://github.com/ibakshay/k8s-infra/pkgs/container/greenhouse-extensions-integration-test).
> Add workflow for building and publishing integration test Docker image

- kube-monitoring/plugindefinition.yaml
This Pull Request, 
- bumps the `kube-monitoring` Plugindefiniton version
- bumps the helm chart version of `kube-monitoring`
> [kube-monitoring] Bump the kube-monitoring Plugindefinition version

- .github/workflows/helm-lint-test.yaml
This pull request improves our testing process by introducing integration tests to the existing PR workflow. Key changes include:
1. Automated creation of a Kind cluster within the workflow to set up the integration test environment.
2. Execution of integration tests in the locally created Kind cluster.
3. Automated deletion of the Kind cluster upon workflow completion, ensuring clean-up of resources.
This workflow can be tested locally using the `act` tool with the following command:
```shell
act pull_request --container-architecture linux/amd64 -P default=catthehacker/ubuntu:act-latest --job helm-lint-test --workflows .github/workflows/helm-lint-test.yaml --eventpath act_pull_request.json
```
1. `act_pull_request.json` with the following content:
```json
{
"pull_request": {
"number": …
```
>  Enhance PR Workflow with Integration Tests Using Kind Cluster

- doop/ui/jest.config.js
- doop/ui/package-lock.json
- doop/ui/package.json
- doop/ui/src/App.jsx
- doop/ui/src/components/AppContent.jsx
- doop/ui/src/components/AuthProvider.jsx
- doop/ui/src/components/Header.jsx
- doop/ui/src/components/filters/FilterPills.jsx
- doop/ui/src/components/filters/FilterSelect.jsx
- doop/ui/src/components/filters/Filters.jsx
- doop/ui/src/components/shared/FilterPill.jsx
- doop/ui/src/components/shared/HintLoading.jsx
- doop/ui/src/components/shared/HintNotFound.jsx
- doop/ui/src/components/violations/ViolationDetails.jsx
- doop/ui/src/components/violations/ViolationDetailsList.jsx
- doop/ui/src/components/violations/ViolationDetailsPills.jsx
- doop/ui/src/components/violations/ViolationSeverity.jsx
- doop/ui/src/components/violations/ViolationsList.jsx
- doop/ui/src/components/violations/ViolationsListItem.jsx
- doop/ui/src/hooks/useCommunication.js
- doop/ui/src/hooks/useUrlState.js
- doop/ui/tailwind.config.js
this PR switches dependencies from assets server to npm registry for doop UI.
- Change all imports regarding juno packages using a prefix `@cloudoperators/juno-`
e.g. `import ... from "communicator"` ->  `import ... from "@cloudoperators/juno-communicator"` 
- Move juno package from devDependencies to dependencies using the new naming schema.
> chore(doop): use npm deps for juno packages

- heureka/ui/package-lock.json
- heureka/ui/package.json
- heureka/ui/src/components/components/ComponentsList.jsx
- heureka/ui/src/components/components/ComponentsListController.jsx
- heureka/ui/src/components/components/ComponentsListItem.jsx
- heureka/ui/src/components/components/ComponentsTab.jsx
- heureka/ui/src/components/issues/IssuesList.jsx
- heureka/ui/src/components/issues/IssuesListController.jsx
- heureka/ui/src/components/issues/IssuesListItem.jsx
- heureka/ui/src/components/services/ServicesListController.jsx
- heureka/ui/src/components/tabs/TabContext.jsx
- heureka/ui/src/hooks/useQueryClientFn.js
- heureka/ui/src/lib/queries/components.js
- heureka/ui/src/lib/store.js
Add components view. For the first version, as the info related to componentInstance is not available in the API yet, this info is not displayed in the table . It will be added as soon as the info will be available in the API later.
> feat(heureka) : Add components view

- thanos/charts/Chart.yaml
- thanos/charts/templates/compactor.yaml
wrong indent caused helm diff to fail
> chore(thanos): fixing security context indent

- .github/workflows/helm-release.yaml
Change paths for opentelemetry to remove -operator postfix. Variable `chartName` is intended to keep opentelemetry-operator to show relation to upstream chart.
> update(helm-release): change paths for opentelemetry to rm -operator postix as in #320

- .github/CODEOWNERS
- Dockerfile.otel-collector
Dockerfile update for fixed versions Debian and Otel-collector and not latest anymore.
Upgrade from 0.105.0 -> 0.107.0
Update needed for clean image and grok parsing:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34037
> OTEL Logs collector Dockerfile 0.105.0 -> 0.107.0

- thanos/charts/Chart.yaml
- thanos/plugindefinition.yaml
the license headers borked the current version, creating a new one
> chore(thanos): bump version

- heureka/ui/package-lock.json
- heureka/ui/package.json
- heureka/ui/src/components/components/ComponentsList.jsx
- heureka/ui/src/components/filters/FilterSelect.jsx
- heureka/ui/src/components/services/ServicesList.jsx
- As currently live search handling is very expensive with too many API calls, I deactivated that, to be implementated later with having a proper store state update in place
- Give the min column to columns which contains count number in services and components view
> feat(heureka): Remove expensive live search  & improve styling

- .github/licenserc.yaml
- opentelemetry/chart/Chart.yaml
- opentelemetry/chart/templates/tests/test-opentelemetry-config.yaml
- opentelemetry/chart/templates/tests/test-opentelemetry.yaml
- opentelemetry/chart/templates/tests/test-permissions.yaml
- opentelemetry/chart/values.yaml
- opentelemetry/plugindefinition.yaml
- added basic chart testing for core components
[[opentelemetry] make opentelemetry plugin production-ready](https://github.com/cloudoperators/greenhouse-extensions/issues/244)
> [opentelemetry] add testing for plugin

- alerts/ui/package-lock.json
- alerts/ui/package.json
- doop/ui/package-lock.json
- doop/ui/package.json
- heureka/ui/package-lock.json
- heureka/ui/package.json
Apps versions are updated as the renovate PR which includes patch update of testing library is merged recently.
Here is the commit related to the update with renovate:
https://github.com/cloudoperators/greenhouse-extensions/commit/d2ee9efb46f4c34101456c863c1f334d82e9bf79
> chore(doop,alerts,heureka): Update app versions because of renovate patch dependecies update

- alerts/ui/public/index.html
- alerts/ui/src/AppContent.jsx
- alerts/ui/src/api/apiService.js
- alerts/ui/src/components/AsyncWorker.jsx
- alerts/ui/src/components/alerts/AlertsList.jsx
- alerts/ui/src/components/silences/SilenceScheduled.jsx
- alerts/ui/src/helpers.js
- alerts/ui/src/hooks/useAlertmanagerAPI.js
- alerts/ui/src/hooks/useCommunication.js
- alerts/ui/src/hooks/useUrlState.js
This PR addresses the issue caused by the removal of the auth functionality from Supernova, which broke the preselection of the “support_group” filter. Previously, the useUrlFilter hook relied on the auth app being loaded and the user being logged in. This dependency has now been removed.
The filter is now set within the useCommunication hook if it hasn’t been set already, ensuring the correct functionality without relying on the auth app.
Additionally, the fullName in the auth data is now defaulted to “anonymous.” If an auth event is triggered, the auth data will be updated with the correct full name.
> fix(supernova-ui): fix preselected support group

- doop/ui/src/components/Header.jsx
This updates the DOOP UI, as the previous link to `grafana` now has invalid certs
> fix(doop): update plutono link

- logshipper/chart/Chart.yaml
- logshipper/chart/ci/test-values.yaml
- logshipper/chart/templates/fluent-bit-configmap.yaml
- logshipper/plugindefinition.yaml
Wrong indentation not caught by missing test values
> fix(logshipper): wrong indentation for additonalValues & opensearch

- logshipper/chart/Chart.yaml
- logshipper/chart/templates/fluent-bit-configmap.yaml
- logshipper/plugindefinition.yaml
The introduction of the `default_` prefix broke the log routing to the output.
> fix(logshipper): default output did not match

- heureka/plugindefinition.yaml
The repository used in the PluginDefinition did not exist.
I see that the exact version exists here: https://github.com/cloudoperators/heureka/pkgs/container/heureka%2Fcharts%2Fheureka
> fix(heureka): point helmchart to correct repository

- opentelemetry/chart/Chart.yaml
- opentelemetry/chart/templates/smon-filelog.yaml
- opentelemetry/chart/values.yaml
- opentelemetry/plugindefinition.yaml
- bump version
- different label for prometheus scraping
- fixed version for otel-contrib
- 2 years for certs
- enable podMonitor
> Otel updates for scraping

- logshipper/chart/Chart.yaml
- logshipper/chart/templates/fluent-bit-configmap.yaml
- logshipper/plugindefinition.yaml
labels and annotations are not added to the logline
None.
1. Kubernetes Metadata is added to container logs again
2. Kubernetes Labels & Annotations are not added to the logs
:question:
> fix(logshipper): ensures k8s metadata is added

- Dockerfile.otel-collector
- opentelemetry/chart/Chart.yaml
- opentelemetry/chart/ci/test-values.yaml
- opentelemetry/chart/values.yaml
- opentelemetry/plugindefinition.yaml
- **chore(openTelemetry): bumps version of charts to v.114.0**
- **fix(openTelemetry): changes default tag for collectorImage to be 'main'**
> [openTelemetry] Bumps version to v0.114.0

- alerts/charts/Chart.yaml
- alerts/charts/templates/ca-secret-issuer-cert.yaml
- alerts/plugindefinition.yaml
The *-monitoring-ca should not be regenerated on every deploy.
fixes #546
> fix(alerts): avoid reconciliation loop

- opentelemetry/README.md
- opentelemetry/chart/Chart.yaml
- opentelemetry/chart/templates/_ceph-config.tpl
- opentelemetry/chart/templates/_kvm-config.tpl
- opentelemetry/chart/templates/logs-collector.yaml
- opentelemetry/chart/values.yaml
- opentelemetry/plugindefinition.yaml
This PR adds a functionality to enable/disable common log configuration for logs for Ceph and KVM.
Both logtypes can be disabled/enabled in the PluginDefinition. In case of enabling, the logs-collector.yaml will be enriched by KVM/Ceph specific labels, parsing and defined pipelines.
The goal is to reduces the complexity of the logs-collector configuration and provide standard log configuration for common scenarios.
Corresponding Roadmap issue: #515
> [opentelemetry] add templating for ceph and kvm

- .github/workflows/ci-pr-build.yaml
The label `pr-build-chart` will create the package with the tag `${{ env.PR_NUMBER }}-pr`
accordingly the label should look for the tag in a same way, example for a failed action here:  https://github.com/cloudoperators/greenhouse-extensions/pull/575
> fix(action) cleanup charts in a PR with label

- thanos/plugindefinition.yaml
updating Thanos plugindefinition to enable Alertmanager configuration
adding AM Auth toggle to Thanos plugindefinition
/
message: 'Helm template failed: execution error at (thanos/templates/ruler/alertmanager-sso-secret.yaml:8:14): .Values.thanos.ruler.alertmanagers.authentication.ssoCert missing'
/
> fix(thanos) Ruler AM auth - add plugindefinition options

- thanos/charts/Chart.yaml
- thanos/charts/templates/ruler/ruler-svc.yaml
- thanos/charts/values.yaml
- thanos/plugindefinition.yaml
New Thanos Ruler Service resource to allow to add custom labels to it for Proxy server discovery
None
Allows proxy server discovery
issue about not being apple to add labels to governed thanos service 
[/prometheus-operator/issues/7317](https://github.com/prometheus-operator/prometheus-operator/issues/7317)
Potential solution will just to specify a serviceName so when thanos operator tries to reconcile. if it doesn't finds the right service name reconcile fails
> [thanos] add thanos ruler svc for service discovery

- alerts/charts/Chart.yaml
- alerts/charts/ci/test-values.yaml
- alerts/charts/templates/certmanager.yaml
- alerts/charts/values.yaml
- alerts/plugindefinition.yaml
YAML treats strings starting with asterisk in a special way - that's why the dnsNames with wildcards like *.example.local breaks on helm install
> fix(alerts): quote dnsNames starting with asterisk

- thanos/charts/Chart.yaml
- thanos/charts/templates/ruler/ruler-svc.yaml
- thanos/charts/templates/tests/test-permissions.yaml
- thanos/charts/templates/tests/test-thanos-config.yaml
- thanos/plugindefinition.yaml
Ruler service is deployed when `thanos.ruler.enabled` is _**false**_
Adding flow control on `ruler-svc.yaml` to avoid that
> fix(thanos) disable ruler-svc

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/ci/test-values.yaml
- kube-monitoring/charts/templates/_alertmanager-config.yaml.tpl
- kube-monitoring/charts/templates/alertmanager-config.yaml
- kube-monitoring/charts/templates/alertmanager-tls-secret.yaml
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
To enable multiple deployments in the same namespace. Foundation to: #142
> feat(kube-monitoring): ensure unique secret names based on the release

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/ci/test-values.yaml
- kube-monitoring/charts/templates/_alertmanager-config.yaml.tpl
- kube-monitoring/charts/templates/alertmanager-tls-secret.yaml
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
The secret expected to mount is living in the central cluster. The option values still apply.
> fix(kube-monitoring): remove secret reference

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/plugindefinition.yaml
This will take the image version from the kube-prometheus-stack.
Upgrades prometheus-operator to `v0.80.0`
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.80.0
> chore(kube-monitoring): remove prometheus-operator appVersion

- .github/renovate.json
- alerts/plugindefinition.yaml
- kube-monitoring/plugindefinition.yaml
@kengou Please review if this change makes sense.
> fix(renovate): bump kube-monitoring & alerts plugindefinition

- logs/README.md
- logs/charts/Chart.yaml
- logs/charts/ci/test-values.yaml
- logs/charts/templates/logs-collector.yaml
- logs/charts/values.yaml
- logs/plugindefinition.yaml
fixes the rendering of multiple `logs/containerd` pipelines if user enables KVM or Ceph logging.
> fix(logs): condition for kvm and ceph logging

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
This PR addresses several issues with the OpenSearch plugin configuration:
- Removes the admin and kibanaserver users from plugin configuration as they conflict with internally created standard users
- Adjusts permissions and roles for the logs user to ensure proper access
- Updates the plugin to version 1.19.1 for compatibility with latest OpenSearch
- Fixes ServiceMonitor configuration to properly enable metrics collection
No
X
X
> fix(opensearch): fix permissions, remove standard users, upgrade to 1.19.1

- docs/catalog.md
- opensearch/chart/Chart.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchactiongroups.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchclusters.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchcomponenttemplates.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchindextemplates.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchismpolicies.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchroles.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchtenants.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchuserrolebindings.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchusers.yaml
- opensearch/plugindefinition.yaml
This PR updates the OpenSearch CRDs to:
- Use the standard opensearch namespace label instead of the demo-specific demo label
- Change the scope from `Namespaced` to `Cluster` to support use in multiple namespaces
None. 
Currently the plugin cannot be deployed because demo namespace is protected.
> fix(opensearch): Change label and scope for opensearch crds

- opensearch/chart/Chart.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchactiongroups.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchclusters.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchcomponenttemplates.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchindextemplates.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchismpolicies.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchroles.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchtenants.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchuserrolebindings.yaml
- opensearch/chart/crds/opensearch.opster.io_opensearchusers.yaml
- opensearch/plugindefinition.yaml
Switching the CRDs back to `Namespaced` ensures each CR has a valid `metadata.namespace`, which the operator relies on to scope all of its actions.
None
N/A
> fix(opensearch): fix crds scope and remove installCRDs toggle 

- cert-manager/plugindefinition.yaml
the timeout was increased when we updated cert-manager gardener clusters do not allow timeouts with >15s
this reduces the timeout to 15s
is true:
---
:question:
:question:
Enter the issue numbers resolved by …
> feat(cert-manager): reduce timeout for webhooks

- Dockerfile.otel-collector
This updates the Dockerfile for our customised openTelemetry-collector-contrib image. Changes are outlined here for core https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.124.0, and here for the upstream contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.124.1.
---------
Signed off by: Simon Olander (simon.olander@sap.com)
> chore(logs): bumps OpenTelemetry-collector-contrib to v0.124.1

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/templates/dashboard-service.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
Adds a manual `Service` resource for OpenSearch Dashboards to be used for service proxy with the proper labeling. This is a temporary solution until [opensearch-k8s-operator PR #1002](https://github.com/opensearch-project/opensearch-k8s-operator/pull/1002) is merged, which will introduce native support for labels on service resources.
None
None
> feat(opensearch): add manual service for dashboards

- .github/renovate.json
automatic PR creation for 
https://github.com/cloudoperators/greenhouse-extensions/blob/main/Dockerfile.integration-test
```
ARG KUBECTL_VERSION=v1.30.3
ARG GRPC_HEALTH_PROBE_VERSION=v0.4.37
```
https://github.com/cloudoperators/greenhouse-extensions/blob/main/Dockerfile.otel-collector
```
FROM --platform=${BUILDPLATFORM:-linux/amd64} debian:12.10 AS journal
FROM --platform=${BUILDPLATFORM:-linux/amd64} ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.124.1
```
UDPATE
```
ARG YQ_VERSION=v4.45.1
```
> feat(renovate) dockerfile versions

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
Allow to set custom labels for the ServiceMonitor to expose OpenSearch metrics to Prometheus.
None
N/A
> feat(opensearch): add labels for ServiceMonitor

- .github/renovate.json
- Makefile
- pint-config.hcl
- added renovate config for pint and helm versions
- not deleting binaries if version is matching config (helm-docs, pint, helm)
- make pint PLUGIN=kube-monitoring
> feat(repo) make pint

- logs/charts/Chart.yaml
- logs/charts/templates/logs-collector.yaml
- logs/charts/templates/metrics-collector.yaml
- logs/plugindefinition.yaml
The metrics are align with the default values for metrics. By removing the section we ensure the exposing does not happen twice. This behavior can be tested locally with:
- Created a kind cluster
- Installed cert-manager
- Installed the 0.79.0 version of the helm chart for the operator:  ```helm upgrade --install otel-operator open-- telemetry/opentelemetry-operator --version 0.79.0 --set manager.collectorImage.repository=otel/opentelemetry-collector-contrib```
- Created an OpenTelemetry Collector instance:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
name: test
spec:
mode: deployment
config: |
receivers:
otlp:
protocols:
grpc: {}
http: {}
processors:
exporters:
debug: {}
extensions:
service:
pipelines:
metrics:
receivers: [otlp]
processors: [] …
```
> [logs] rm duplicated exposed metrics endpoints

- Makefile
The HELM_DOCS_REPO install url yields a 404 on the workflow run https://github.com/cloudoperators/greenhouse-extensions/actions/runs/14927089409/job/41934304611?pr=766
Seemingly from the list of releases we need to use x86_64 instead, see https://github.com/norwoodj/helm-docs/releases/tag/v1.14.2
---------
Signed off by: Simon Olander (simon.olander@sap.com)
> fix(.github): updates url for HELM_DOCS_REPO to resolve 404

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/templates/certificates.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
- opensearch/test-dependencies.yaml
This change:
- Disables the operators automatic generation of self-signed certificates
- Creates three new certificates:
- `opensearch-http-cert` for the REST API
- `opensearch-transport-cert` for node-to-node communication
- `opensearch-admin-cert` for admin operations
N/A
N/A
> feat(opensearch): support cert-manager certs and disable self-signed

- audit-logs/README.md
- audit-logs/charts/Chart.yaml
- audit-logs/charts/values.yaml
- audit-logs/plugindefinition.yaml
This resolves an error where there were missing 'pluginDefinition' fields and 'values.yaml' for e.g. '.Values.auditLogs.prometheus.additionalLabels'.
---------
Signed off by: Simon Olander (simon.olander@sap.com)
> fix(audit-logs): adds missing 'auditLogs.prometheus*' values to pluginDefinitions, values

- .github/licenserc.yaml
This ensures the license headers added to new files have the current year set.
> fix(actions): ensure current year for new spdx refs

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
latest patches to `kubectl` CLI in integration-test image are throwing some errors
```
not ok 4 Verify creation of required custom resource definitions (CRDs) for gno-prometheus-operator
```
> fix(kube-monitoring) pin integration-test version

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/templates/certificates.yaml
- opensearch/chart/templates/issuer.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
This PR includes the following changes:
- Refactored certificate Helm charts: moved more configuration into `values.yaml`
- Split issuer and certificate definitions into separate files
- Made the HTTP DNS name configurable via the plugin interface
> feat(opensearch): allow configuring HTTP DNS names via plugin

- thanos/plugindefinition.yaml
adding alert labels to prometheus rules for observability team
```
support_group: observability
service: metrics
```
> fix(thanos) thanos alert labels

- opensearch/README.md
- opensearch/chart/Chart.yaml
- opensearch/chart/ci/test-values.yaml
- opensearch/chart/templates/users-secret.yaml
- opensearch/chart/values.yaml
- opensearch/plugindefinition.yaml
This PR improves the OpenSearch cluster configuration by adding support for configurable user credentials with failover capabilities.
- Configurable user credentials: New `usersCredentials` section in values.yaml allowing override of usernames and passwords for OpenSearch users from Plugin
- Restructured user configuration to separate credentials from user role definitions
- Failover user support: Secondary user (`logs2`) configuration for redundancy
> feat(opensearch): add configurable user credentials

- .github/workflows/helm-lint-test.yaml
to avoid having ready to merge PRs that may have conflicting plugindefinition version with main branch we can re-trigger this git action on all open PRs
> git action helm test trigger on push to main

- .github/renovate.json
trying to avoid this, helm-lint-test or plugindefinitionbump git actions don't support renovate PRs updating charts in multiple plugins
> fix(renovate) group helm update by plugin

- .github/workflows/sync-plugindefinition.yaml
https://github.com/cloudoperators/greenhouse-extensions/pull/963
git-action can not find Chart.yaml since it is located in chart instead of charts
> fix(git-actions) sync-plugindef support chart/charts folder structure

- .github/workflows/helm-lint-test.yaml
re-run helm test on PRs when changes are made to main to avoid merging same chart/plugindeifinition versions
> fix(gh-actions) PR target sync helm lint test

- .github/workflows/ci-pr-build.yaml
- .github/workflows/helm-release.yaml
- audit-logs/test-dependencies.yaml
- logs/README.md
- logs/charts/Chart.lock
- logs/charts/Chart.yaml
- logs/charts/ci/test-values.yaml
- logs/charts/templates/logs-collector.yaml
- logs/charts/templates/metrics-collector.yaml
- logs/charts/templates/smon.yaml
- logs/charts/values.yaml
- logs/plugindefinition.yaml
- change chart name to make reference to upstream-chart more clear
- update appVersion accordingly to https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/Chart.yaml
- update maintainers
> chore(logs): fix naming for operator, update maintainers

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
specific alert names can be disabled from value file
see template
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml#L366
absent metrics operator highlighting unused prometheus metrics
> fix(kube-monitoring) disable unused alert/metrics

- logs/charts/Chart.yaml
- logs/charts/crds/opentelemetry.io_opentelemetrycollectors.yaml
- logs/plugindefinition.yaml
In order to leverage host-level things in a cluster, for instance when we want to access auditd or systemd files/processes, we need to enable the `hostPID` setting. This is by default not permitted in the otelcol CRDs.
This adds a second CRD version "v2beta1" with this field enabled. 
---------
on-behalf-of: @SAP Simon Olander (simon.olander@sap.com)
> feat(logs): adds v2beta1 version to the otelcol CRD to support hostPID

- kubeconfig-generator/chart/Chart.yaml
- kubeconfig-generator/plugindefinition.yaml
This fixes a known issue with kubeconfig-generator
---
Clusters that do not have a public `/version` endpoint will not be uploaded to the registry anymore.
> feat(kubeconfig-generator): Exclude clusters without public version ep

- logs/charts/Chart.yaml
- logs/charts/perses-dashboards/otel-logs.json
- logs/plugindefinition.yaml
Due to recent metrics changes (e.g. adding the suffix `_total` to queries) in OpenTelemetry the Perses Dashboard needed to be fixed. Some visualization e.g. for metrics that were not used anymore were also removed as well a filter for grouping.
> fix(logs): fix perses dashboard

- opensearch/chart/Chart.yaml
- opensearch/plugindefinition.yaml
This PR updates the OpenSearch plugindefinition to support overriding key image and version fields. With these users can specify private registries, mirrors, or custom images for all major OpenSearch components.
> feat(opensearch): add image and version override options to plugindefinition

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/perses-dashboards/prometheus.json
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
alert a throwing absent metric on `prometheus_sd_refresh_failures_total`
this metric may only be present when actual sd config refresh are failing but greenhouse setup only uses selectors
> fix(kube-monitoring) disable PrometheusSDRefreshFailure

- logs/charts/Chart.yaml
- logs/charts/alerts/collector-alerts.yaml
- logs/playbooks/LogsOTelLogsDecreasing.md
- logs/plugindefinition.yaml
This adds alert and playbook in case logs are significantly decreasing to detect problems of log ingestion or performance issues upfront.
> feat(logs): add alert and playbook for decreasing Logs

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/templates/absent-metrics-operator/alert.yaml
- kube-monitoring/plugindefinition.yaml
support_group: observability
service: metrics
those labels are generally passed by users and should not be hardcoded
> fix(kube-monitoring) remove hardcoded labels

- thanos/charts/Chart.yaml
- thanos/charts/templates/blackbox-exporter/servicemonitor.yaml
- thanos/charts/templates/servicemonitor.yaml
- thanos/plugindefinition.yaml
thanos service monitor need matching label of kube-monitoring plugin. to avoid conflicting labels we won't include thanos plugin label on serviceMonitor resource
> fix(thanos) remove plugin label from smon

- kube-monitoring/charts/Chart.yaml
- kube-monitoring/charts/values.yaml
- kube-monitoring/plugindefinition.yaml
Allow for both labels and annotations to set exposed services. This is only for a transition process. 
This PR concerns only `kube-monitoring`
None
https://github.com/cloudoperators/greenhouse/issues/1017
Related PRs:
- https://github.com/cloudoperators/greenhouse-extensions/pull/1134
- https://github.com/cloudoperators/greenhouse-extensions/pull/1136
> feat(kube-monitoring): allow both labels and annotations to define exposed services

- exposed-services/README.md
- exposed-services/charts/v1.0.0/exposed-service/Chart.yaml
- exposed-services/charts/v1.0.0/exposed-service/templates/_helpers.tpl
- exposed-services/charts/v1.0.0/exposed-service/templates/service.yaml
- exposed-services/charts/v1.0.0/exposed-service/values.yaml
- exposed-services/charts/v2.0.0/exposed-service/Chart.yaml
- exposed-services/charts/v2.0.0/exposed-service/templates/_helpers.tpl
- exposed-services/charts/v2.0.0/exposed-service/templates/service.yaml
- exposed-services/charts/v2.0.0/exposed-service/values.yaml
- openbao/charts/openbao/Chart.yaml
- openbao/charts/openbao/templates/server-service.yaml
- plutono/README.md
- plutono/charts/Chart.yaml
- plutono/charts/values.yaml
- thanos/README.md
- thanos/charts/Chart.yaml
- thanos/charts/templates/_helpers.tpl
- thanos/charts/templates/compactor/service.yaml
- thanos/charts/templates/query/service.yaml
- thanos/charts/templates/ruler/service.yaml
- thanos/charts/templates/store/service.yaml
- thanos/charts/values.yaml
- thanos/plugindefinition.yaml
Allow for both labels and annotations to set exposed services. This is only for a transition process. `kube-monitoring` and `perses` changes will be done in seperate PR.
None
https://github.com/cloudoperators/greenhouse/issues/1017
Related PRs:
- https://github.com/cloudoperators/greenhouse-extensions/pull/1135
- https://github.com/cloudoperators/greenhouse-extensions/pull/1136
> feat(plugins): allow both labels and annotations to define exposed services

- logs/charts/Chart.yaml
- logs/charts/templates/_kvm-config.tpl
- logs/plugindefinition.yaml
This fixes the current parsing errors with inconsistent timestamps:
- date and time separated by `T` or space
- milliseconds and second separated by comma (`,`) or dot (`.`)
Further parsing should be implemented in a follow-up PR once the inconsistency can be removed.
> fix(logs): fix parsing for kvm logs

- logs/charts/Chart.yaml
- logs/charts/templates/failover-config.tpl
- logs/charts/templates/logs-collector.yaml
Fix: adding missing config setting num_consumers to otel config, as the otel-collector is crashlooping
last release is crashlooping
> fix add missing num_consumers to otel config
