.github/workflows/stale.yaml

feat(gh-actions) add stale gh-actions

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/values.yaml
kube-monitoring/plugin.yaml

ensures one unique metric per container + container label exists

fix(cAdvisor metrics): more useful metric relabeling

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/values.yaml
kube-monitoring/plugin.yaml

back to default context

---

heureka/ui/package-lock.json
heureka/ui/package.json

- Set the MFE public
- Remove stars from the peerDependencies
- Set some peerDependencies version equal to the devDependencies
- Fixes some typos appProps description
- Patch version upgrade

fix(heureka): make app public, remove stars from peerDependencies and some typos

---

doop/ui/package-lock.json
doop/ui/package.json

- Set the MFE public
- Set missing peerDependencies
- Fixes some typos appProps description
- Patch version upgrade

fix(doop): make app public, remove stars from peerDependencies and some typos

---

doop/ui/package.json

- Fix existing version removing react-query (and others) to fix the e2e tests
- Upgrade version

fix(doop): remove react-query form peerDependencies do tue problem in runtime

---

.github/workflows/3rd-party-licenses.yaml
.gitignore
alerts/README.md
alerts/ui/README.md
doop/README.md
doop/ui/README.md
heureka/ui/README.md

This PR:
- Added workflow to check all 3rd party licenses from all MFEs living in ui folder
- Adds an apache badge to all greenhouse MFEs since it is Juno standard and triggers the workflow describe above

feat(workflow) added a workflow to check all 3rd party licences from all MFEs

---

alerts/ui/package-lock.json
alerts/ui/package.json
doop/ui/package-lock.json
doop/ui/package.json
heureka/ui/package-lock.json
heureka/ui/package.json

is true:
---
:question:
:question:
1. :question:
:question:

fix(alerts,heureka,doop): Update sass package to remove CWE-1050

---

kubeconfig-generator/chart/Chart.yaml
kubeconfig-generator/plugin.yaml

chore: Update kubeconfig-generator

---

alerts/ui/README.md
doop/ui/README.md
heureka/ui/README.md

- add 'built wiht juno' badge in the app readmes with the self hosted svg
Related Tickets & Documents
- Related Issue https://github.com/cloudoperators/juno/issues/59

feat(apps) add 'built wiht juno' badge in the app readmes with the self hosted svg

---

heureka/ui/package-lock.json
heureka/ui/package.json

Update the package-lock.json to solve the errors (e.g missing darwin pkg error) while building the project locally on mac. 
Apparently some packages are not updated. For this purpose I performed the following commands:
- npm cache clean --force
- npm install
As it is shown in the changes, the `sass` and `graphql-request` as direct packages are updated and the rest are the depended packages.

fix (heureka): Update the package-lock.json

---

heureka/ui/package-lock.json
heureka/ui/package.json
heureka/ui/src/lib/queries/issueMatches.js

This file includes the new query. It was missed in the last PR and therefore the test on heureka pipeline is failed.

fix(heureka): Add the left behind issueMatches.js file

---

alerts/ui/package-lock.json
doop/ui/package-lock.json

- Upgrade of dedicated dependencies to fix vulnerabilities reported by audit
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

chore(doop/alerts): update deps

---

alerts/ui/src/components/CustomAppShell.jsx

The TopNavigation of alerts is now also shown in the embedded mode.
fixes: #185

fix(alerts/ui): TopNav is now also shown in the embedded mode

---

alerts/ui/package-lock.json
alerts/ui/package.json
alerts/ui/src/components/CustomAppShell.jsx

Increment version for last fix.

fix(alerts/ui): increment version for last fix.

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/plugin.yaml

This will enable thanos sidecar functionality on kube-monitoring side.

feat(thanos): enabling thanos sidecar functionality

---

opentelemetry-operator/chart/Chart.yaml

---
Bump chart after last PR: https://github.com/cloudoperators/greenhouse-extensions/pull/202

[opentelemetry-operator] bump chart

---

alerts/ui/package-lock.json
alerts/ui/package.json
alerts/ui/src/App.jsx
alerts/ui/src/components/alerts/AlertStatus.jsx

In the alerts overview silences which are inhibited have now a summary what alert is the Inhibitor.
fixes #198 #201

feat(alerts/ui): show summary instead of fingerprint of inhibitor

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/templates/logs-collector.yaml
opentelemetry-operator/chart/templates/metrics-collector.yaml

[opentelemetry-operator] move image to col spec, bump chart

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/templates/logs-collector.yaml
opentelemetry-operator/chart/templates/metrics-collector.yaml
opentelemetry-operator/chart/values.yaml

Template OpenTelemetry Collector Image so it can be passed through the PluginDefinition.

[opentelemetry-operator] template image, bump chart version

---

.github/CODEOWNERS

is true:
---
:question:
:question:
1. :question:
:question:

chore(codeowners): add greenhouse-observability team

---

cert-manager/charts/v1.11.0/cert-manager/Chart.lock

is true:
---
:question:
:question:
1. :question:
:question:

chore(cert-manager): regenerate Chart.lock to trigger chart upload

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/templates/logs-collector.yaml
opentelemetry-operator/plugindefinition.yaml

Template OpenSearch Index so User can define the index individually.

[opentelemetry-operator] template otel index

---

.github/renovate.json

https://docs.renovatebot.com/configuration-options/#bumpversion
is true:
---
:question:
:question:
1. :question: …

feat(renovate config): increase patch version of the chart in question

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/templates/logs-collector.yaml
opentelemetry-operator/chart/templates/smon-filelog.yaml
opentelemetry-operator/plugindefinition.yaml

- fix conditonal rendering of PodMonitor
- bump chart version

[opentelemetry-operator] fix logic for pod monitor

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/crds/crd-opentelemetrycollector.yaml
opentelemetry-operator/plugindefinition.yaml

This PR updates the OpenTelemetryCollector CRD to the version and also includes alpha and beta.

[opentelemetry-operator] update otelcol crd

---

.github/renovate.json

https://docs.renovatebot.com/configuration-options/#bumpversion
is true:
---
:question:
:question:
1. :question: …

chore(renovate-config): Increase major and minor chart versions

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

chore(renovate-config): use additionalBranchPrefix

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

fix(renovate-config): Invalid JSON

---

thanos/README.md

better useability of documentation with internal link to actual sidecar configuration
some fix with linebreaks

docs(thanos): fixing some formatting and improve internal link

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/crds/crd-opentelemetry.io_opampbridges.yaml
opentelemetry-operator/chart/crds/crd-opentelemetrycollector.yaml
opentelemetry-operator/chart/crds/crd-opentelemetryinstrumentation.yaml
opentelemetry-operator/plugindefinition.yaml

-  add appVersion
- update CRDs with correct source: https://github.com/open-telemetry/opentelemetry-operator/tree/main/config/crd/bases
(instead of: https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator/conf/crds)

[opentelemetry-operator] update CRDs

---

heureka/ui/jest.config.js
heureka/ui/package-lock.json
heureka/ui/package.json
heureka/ui/src/App.js
heureka/ui/src/App.test.js
heureka/ui/src/components/filters/FilterPills.jsx
heureka/ui/src/components/filters/FilterSelect.jsx
heureka/ui/src/components/filters/Filters.jsx
heureka/ui/src/components/issues/IssuesList.jsx
heureka/ui/src/components/issues/IssuesListController.jsx
heureka/ui/src/components/issues/IssuesListItem.jsx
heureka/ui/src/components/services/ServicesList.jsx
heureka/ui/src/components/services/ServicesListController.jsx
heureka/ui/src/components/services/ServicesListItem.jsx
heureka/ui/src/components/shared/HintLoading.jsx
heureka/ui/src/components/shared/HintNotFound.jsx
heureka/ui/src/components/tabs/TabContext.jsx
heureka/ui/src/hooks/useCommunication.js
heureka/ui/src/hooks/useUrlState.js
heureka/ui/tailwind.config.js

Installing juno-ui-components npm package through `npm add @cloudoperators/juno-ui-components` and update all relevant imports

feat(heureka) : switch to npm deps for juno packages

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/crds/crd-opentelemetry.io_opampbridges.yaml
opentelemetry-operator/chart/crds/crd-opentelemetrycollector.yaml
opentelemetry-operator/chart/crds/crd-opentelemetryinstrumentation.yaml
opentelemetry-operator/plugindefinition.yaml

Adding annotations for CRDs which has to be done manually according to the [documentation](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md#0560-to-0570).

[opentelemetry-operator] add annotation for helm, bump chart

---

plutono/README.md

is true:
---
:question:
:question:
1. :question:
:question:

docs(plutono): readme formatting

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/_datasource.tpl
kube-monitoring/charts/templates/alertmanager-config.yaml
kube-monitoring/charts/templates/datasource-secret.yaml
kube-monitoring/charts/values.yaml

is true:
---
Replace any :question: below with information about your pull request.
This pull request adds an optional secret to the kube-monitoring chart that contains the data source configuration for Plutono to import.
None
None
:question:

feat(kube-monitoring): create plutono datasource secret

---

.github/workflows/helm-release.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(plutono): add to publishing path

---

.github/workflows/helm-release.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(plutono): add to more publishing paths

---

plutono/README.md

is true:
---
:question:
:question:
1. :question:
:question:

doce(plutono): add note about data sources in dashboards

---

plutono/charts/Chart.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(plutono): update chart source

---

.github/licenserc.yaml

is true:
---
The license headers can generate empty manifests, which prevents helm from templating.  
```
---
---
---
---
---
```
`message: 'Helm install/upgrade failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set'
`
Describe what features are broken by this pull request and why, if …

chore(licenserc): ignore plutono charts

---

plutono/charts/Chart.yaml
plutono/charts/templates/clusterrole.yaml
plutono/charts/templates/clusterrolebinding.yaml
plutono/charts/templates/configSecret.yaml
plutono/charts/templates/configmap-dashboard-provider.yaml
plutono/charts/templates/configmap.yaml
plutono/charts/templates/deployment.yaml
plutono/charts/templates/extra-manifests.yaml
plutono/charts/templates/headless-service.yaml
plutono/charts/templates/hpa.yaml
plutono/charts/templates/ingress.yaml
plutono/charts/templates/networkpolicy.yaml
plutono/charts/templates/poddisruptionbudget.yaml
plutono/charts/templates/podsecuritypolicy.yaml
plutono/charts/templates/pvc.yaml
plutono/charts/templates/role.yaml
plutono/charts/templates/secret-env.yaml
plutono/charts/templates/secret.yaml
plutono/charts/templates/service.yaml
plutono/charts/templates/serviceaccount.yaml
plutono/charts/templates/servicemonitor.yaml
plutono/charts/templates/statefulset.yaml
plutono/plugindefinition.yaml

The license headers added at the top can prevent helm from install the release as this could be the only content in the yaml file.
is true:
---
related #293 
:question:
1. :question:
Provide any other important details …

fix(plutono): avoid empty manifests with license only

---

heureka/ui/package-lock.json
heureka/ui/package.json
heureka/ui/src/components/components/ComponentsList.jsx
heureka/ui/src/components/components/ComponentsListController.jsx
heureka/ui/src/components/issues/IssuesList.jsx
heureka/ui/src/components/issues/IssuesListController.jsx
heureka/ui/src/components/services/ServicesList.jsx
heureka/ui/src/components/services/ServicesListController.jsx
heureka/ui/src/components/shared/ListController.jsx

Refactor controllers as they have the same implementations with different parameters. This way some changes should not be applied in three different files!

feat(heureka): Refactor controllers and reduce redundencies

---

kube-monitoring/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(kube-monitoring): bump plugindefinition

---

openbao/plugindefinition.yaml

is true:
---
Added an extension for openbao secrets manager
- None -
1. - None -
This is an initial …

Added openbao plugin definition

---

.github/workflows/helm-release.yaml
thanos/charts/Chart.yaml
thanos/plugindefinition.yaml

Switching to external image repository and adding to helm build workflow

chore(thanos): new image repository and workflow added

---

.github/workflows/docker-build.yaml
Dockerfile.otel-collector

is true:
---
:question:
:question:
1. :question:
:question:

fix(docker-build): update gh-action and otel Dockerfile

---

Dockerfile.integration-test

is true:
---
:question:
:question:
1. :question:
:question:

[FIX]bump k8s version in Dockerfile.integration-test

---

opentelemetry-operator/chart/Chart.yaml
opentelemetry-operator/chart/templates/logs-collector.yaml
opentelemetry-operator/plugindefinition.yaml

[opentelemetry-operator] bugfixing

---

heureka/ui/package-lock.json
heureka/ui/package.json
heureka/ui/src/components/components/ComponentsList.jsx
heureka/ui/src/components/components/ComponentsListItem.jsx

Pull Request Details
Adds the number of running instances per component to the overview
Issues Fixed
closes https://github.com/cloudoperators/heureka/issues/102

#314 feat(heureka/ui): added total instances to component list view

---

heureka/plugindefinition.yaml

is true:
---
Adds a helm-chart for heureka service
:question:
1. Now there's also a service helm-chart for heureka …

feat: Added a helm chart in the heureka plugin definition

---

.github/CODEOWNERS
heureka-scanner-k8s-assets/plugindefinition.yaml
heureka-scanner-keppel/plugindefinition.yaml
heureka-scanner-nvd/plugindefinition.yaml

is true:
---
Adds 3 new plugin scanners for Haureka
:question:
1. :question:
:question:

feat: Added plugins for Heureka scanners

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/values.yaml
kube-monitoring/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

feat(kube-monitoring): configure kube monitoring component scrapers

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/datasource-secret.yaml
thanos/charts/templates/tests/test-thanos-config.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(kube-monitoring): add file type to plutono datasource secret

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/_datasource.tpl
kube-monitoring/charts/templates/datasource-secret.yaml
kube-monitoring/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(kube-monitoring): ensure unique file names in plutono

---

opentelemetry/chart/Chart.yaml
opentelemetry/plugindefinition.yaml

Trigger creating package creation after workflow changes

[opentelemetry] bump chart to trigger

---

alerts/charts/Chart.yaml
alerts/charts/templates/am-ca-bundle-secret.yaml
alerts/charts/templates/ca-secret-issuer-cert.yaml

is true:
---
The secrets containing the tls configuration disappeared after some time because the helm hooks deleted them. This happened unintentionally.
:question:
1. :question:
Provide any other important details …

fix(alerts): remove hook-delete-policy to keep resources

---

plutono/README.md
plutono/charts/Chart.yaml
plutono/charts/values.yaml
plutono/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(plutono): update docs and include resources across namespaces

---

alerts/charts/Chart.yaml
alerts/charts/values.yaml
alerts/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

feat(alerts): allow cors delete on alertmanager ingress

---

alerts/charts/Chart.yaml
alerts/charts/templates/am-ca-bundle-secret.yaml
alerts/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(alerts): move the variable declaration and encode all

---

alerts/ui/package-lock.json
alerts/ui/package.json
alerts/ui/src/components/CustomAppShell.jsx
alerts/ui/src/components/alerts/Alert.jsx
alerts/ui/src/components/alerts/AlertDetail.jsx
alerts/ui/src/components/alerts/AlertStatus.jsx
alerts/ui/src/components/alerts/shared/AlertSilencesList.jsx
alerts/ui/src/components/alerts/shared/AlertTimestamp.jsx
alerts/ui/src/components/filters/FilterPills.jsx
alerts/ui/src/components/filters/FilterSelect.jsx
alerts/ui/src/components/silences/ExpireSilence.jsx
alerts/ui/src/components/silences/RecreateSilence.jsx
alerts/ui/src/components/silences/SilenceNew.jsx
alerts/ui/src/helpers.js
alerts/ui/src/hooks/useAppStore.js
alerts/ui/src/hooks/useUrlState.js
alerts/ui/src/lib/createAlertsSlice.js
alerts/ui/src/lib/createFiltersSlice.js
alerts/ui/src/lib/createSilencesSlice.js

- Filtered Pills can now be de- and reactivated
- In Alerts Details Silences can now be expired or recreated
Active filter pills can now be clicked to deactivate them and clicked again to activate them.
closes #200 #274 #344

feat(alerts/ui): improvements for filters and details 

---

.github/CODEOWNERS

is true:
---
:question:
:question:
1. :question:
:question:

feat: update temas in codeowners

---

.github/workflows/build-push-supernova-image.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(supernova image) fix trivy scan

---

.github/workflows/build-push-supernova-image.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(supernova-image) add sha as tag

---

opentelemetry/chart/Chart.yaml
opentelemetry/chart/templates/dashboard-json-configmap.yaml
opentelemetry/chart/templates/dashboards/otel-logs.json
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/plugindefinition.yaml

Added labels according to [OpenTelemetry Kubernetes specification](https://opentelemetry.io/docs/specs/semconv/resource/k8s/)

adding otel specs k8s labels

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/pmon.yaml
kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml
kube-monitoring/charts/templates/tests/test-permissions.yaml
kube-monitoring/plugindefinition.yaml

services with a port metrics are getting collected now

feat(kube-monitoring): adding default pmon

---

alerts/ui/package-lock.json
alerts/ui/package.json
alerts/ui/src/lib/createFiltersSlice.js
alerts/ui/src/lib/createFiltersSlice.test.js
alerts/ui/src/lib/createSilencesSlice.js
alerts/ui/src/lib/createSilencesSlice.test.js

Repaired tests and typo in state

fix(ui): fix return value of parse methods and fixed one test

---

Dockerfile.otel-collector
opentelemetry/chart/Chart.yaml
opentelemetry/chart/templates/clusterrole.yaml
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/chart/values.yaml
opentelemetry/plugindefinition.yaml

- fixing the grok parsing for the transform pipelines

fix(opentelemetry) fixing parsing errors, updating images

---

opentelemetry/chart/values.yaml

disable crds, handled by greenhouse

[otel] disable crds

---

opentelemetry/chart/Chart.yaml
opentelemetry/plugindefinition.yaml

feat(open-telemetry): bump versions

---

plutono/charts/Chart.yaml
plutono/charts/templates/_pod.tpl
plutono/plugindefinition.yaml

To make it functional with the service proxy. Fixes https://github.com/cloudoperators/greenhouse/issues/407

plutono: serve from api server sub path

---

plutono/charts/Chart.yaml
plutono/plugindefinition.yaml

Upgrade Go to 1.22.6
Upgrade Alpine to 3.20(.2)

plutono: update plutono release to v7.5.33

---

.github/configs/helm-lint.yaml
.github/configs/helm-test.yaml
opentelemetry/chart/Chart.yaml
opentelemetry/chart/dashboards/otel-logs.json
opentelemetry/plugindefinition.yaml

To function with different datasources.

opentelemetry: datasource variable for dashboard + add to gh-actions

---

plutono/README.md

To be added to the operations bundles.

docs(plutono): How to create dashboards

---

plutono/charts/Chart.yaml
plutono/plugindefinition.yaml

https://github.com/credativ/plutono/releases/tag/v7.5.34

chore(deps): update plutono app to v7.5.34

---

logshipper/chart/Chart.yaml
logshipper/chart/values.yaml
logshipper/plugindefinition.yaml

is true:
---
- The upstream Helm test hook keep failing.
- This happens because the pod is not cleaned up after the test
none
1. disabled the helm tests of the upstream fluent-bit chart …

fix(logshipper): disable testFramework

---

heureka-scanner-k8s-assets/plugindefinition.yaml
heureka-scanner-keppel/plugindefinition.yaml
heureka-scanner-nvd/plugindefinition.yaml

is true:
---
- Helm Chart references included `docker pull` command
:question:
1. :question: …

fix(heureka): fix repository reference in heureka scanners

---

heureka/plugindefinition.yaml

is true:
---
Fixes the double port reference for prometheus in the helm chart
:question:
1. Fixes the double port reference for prometheus in …

upd(heureka): Bump up plugin versions for fixing the double port expose

---

.github/CODEOWNERS

There are no UI components in here anymore.

chore(codeowners): remove team frontend from alerts/

---

opentelemetry/README.md

docs(opentelemetry): add more context

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

feat(renovate): update ingress, external-dns plugin definition 

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

fix(renovate): external-dns lookup string in renovate

---

.github/renovate.json

revert the depNameTemplate
fir lookup in extractVersionTemplate
is true:
---
:question:
:question:
1. :question: …

fix(renovate): external-dns lookup in renovate

---

opentelemetry/chart/Chart.yaml
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/plugindefinition.yaml

fix(opentelemetry) bugfixing wrong label for k8sevents

---

opentelemetry/chart/Chart.yaml
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/plugindefinition.yaml

fixing wrong debug lvl due to https://github.com/open-telemetry/opentelemetry-collector/issues/11337

fix(opentelemetry) exporter debug lvl

---

opentelemetry/README.md
opentelemetry/chart/Chart.yaml
opentelemetry/chart/alerts/collector-alerts.yaml
opentelemetry/chart/alerts/operator-alerts.yaml
opentelemetry/chart/ci/test-values.yaml
opentelemetry/chart/templates/_helpers.tpl
opentelemetry/chart/templates/alerts.yaml
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/chart/templates/metrics-collector.yaml
opentelemetry/chart/templates/pmon-filelog.yaml
opentelemetry/chart/templates/secret.yaml
opentelemetry/chart/templates/smon.yaml
opentelemetry/chart/values.yaml
opentelemetry/plugindefinition.yaml

- Removes redundant values from values.yaml
- Refactored and changed a few values of the values.yaml, added comments, updated references.
- Changed filtering logic for alerts
- Bumps version

[opentelemetry] Clean up of the helm values and structure

---

alerts/charts/Chart.yaml
alerts/charts/values.yaml
alerts/plugindefinition.yaml

https://github.com/prometheus/alertmanager/pull/3045

feat(alerts): enable receiver name in metrics

---

.github/CODEOWNERS
Dockerfile.integration-test

relates to https://github.com/bats-core/bats-core/issues/1024#issuecomment-2508720845
Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>
is true:
---
:question:
:question:
Enter the issue numbers …

chore(integration-test): update bats version to 1.11.1

---

.github/CODEOWNERS
.github/workflows/ci-pr-build.yaml
.github/workflows/helm-release.yaml
perses/charts/Chart.yaml
perses/charts/values.yaml

Correct the chart name in the Perses Helm chart and update CI workflows to include the Perses chart directory.

fix(Perses): chart name and update CI workflows

---

Dockerfile.otel-collector
opentelemetry/chart/Chart.yaml
opentelemetry/chart/values.yaml
opentelemetry/plugindefinition.yaml

bump version to include failover connector
also testing #555

chore(opentelemetry) bump version

---

plutono/charts/Chart.yaml
plutono/charts/templates/_pod.tpl
plutono/plugindefinition.yaml

Adjust the Service URL format based on this PR https://github.com/cloudoperators/greenhouse/pull/840

fix(plutono): update service URL format

---

opentelemetry/README.md
opentelemetry/chart/Chart.yaml
opentelemetry/chart/ci/test-values.yaml
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/chart/templates/secret.yaml
opentelemetry/chart/values.yaml
opentelemetry/plugindefinition.yaml

feat(opentelemetry) add failover

---

kube-monitoring/README.md
kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/_alertmanager_relabel.yaml.tpl
kube-monitoring/charts/templates/_helper.tpl
kube-monitoring/charts/templates/alertmanager-config.yaml
kube-monitoring/charts/templates/dashboard-configmap.yaml
kube-monitoring/charts/templates/podmonitor-sd.yaml
kube-monitoring/charts/values.yaml
kube-monitoring/plugindefinition.yaml

Switch from label selector to annotation.

feat(kube-monitoring): refine pod service discovery

---

.github/renovate.json

Fixing renovate error message: ``` "message": "packageRules[5]: Each packageRule must contain at least one match* or exclude* selector. Rule: {\"ignorePaths\":[\"**/cert-manager/charts/**\"]}" ```
:question:
:question:
1. :question:
:question:

fix(renovate) linting issue

---

kubeconfig-generator/chart/Chart.yaml
kubeconfig-generator/plugindefinition.yaml

is true:
---
:question:
:question:
1. Cluster resources that are not in a Ready state are skipped …

chore(kubeconfig-generator): bump chart & app version

---

alerts/charts/Chart.yaml
alerts/charts/templates/tests/test-alerts-config.yaml
alerts/charts/templates/tests/test-alerts.yaml
alerts/plugindefinition.yaml

Aligned the chart test resources on https://github.com/cloudoperators/greenhouse-extensions/pull/656 and https://github.com/cloudoperators/greenhouse-extensions/pull/637

chore(alerts): improve chart tests

---

.github/workflows/ci-pr-build.yaml
service-proxy/charts/1.0.0/service-proxy/Chart.yaml
service-proxy/charts/1.0.0/service-proxy/ci/test-values.yaml
service-proxy/charts/1.0.0/service-proxy/templates/_helpers.tpl
service-proxy/charts/1.0.0/service-proxy/templates/ingress.yaml
service-proxy/charts/1.0.0/service-proxy/templates/oauth2-proxy-deployment.yaml
service-proxy/charts/1.0.0/service-proxy/templates/oauth2-proxy-ingress.yaml
service-proxy/charts/1.0.0/service-proxy/templates/oauth2-proxy-service.yaml
service-proxy/charts/1.0.0/service-proxy/values.yaml

is true:
---
:question:
:question:
1. :question:
:question:

feat(service-proxy): secure endpoint with oauth2-proxy

---

service-proxy/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(service-proxy): bump plugindefinition version

---

alerts/charts/Chart.yaml
alerts/charts/templates/certmanager.yaml
alerts/charts/templates/tests/test-alerts-config.yaml
alerts/plugindefinition.yaml

This will not prevent the cert-manager to create the secrets.

fix(alerts): match prometheus root issuer

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

feat(renovate): bump perses plugindefinition automatically

---

kube-monitoring/charts/Chart.yaml
kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml

If one component is disabled, the test should not be performed.

chore(kube-monitoring): add conditions to chart tests

---

opentelemetry/README.md
opentelemetry/chart/Chart.yaml
opentelemetry/chart/ci/test-values.yaml
opentelemetry/chart/templates/failover-config.tpl
opentelemetry/chart/templates/logs-collector.yaml
opentelemetry/chart/templates/secret.yaml
opentelemetry/chart/values.yaml
opentelemetry/plugindefinition.yaml

Implements #592: allows users to enable/disable the failover-mechanism in the Plugin Definition

feat(opentelemetry) add enable/disable for failover

---

service-proxy/charts/1.0.0/service-proxy/Chart.yaml
service-proxy/charts/1.0.0/service-proxy/templates/oauth2-proxy-ingress.yaml
service-proxy/plugindefinition.yaml

is true:
---
missing nginx prefix on the oauth2-proxy ingress annotations
missing nginx prefix on the oauth2-proxy ingress annotations
1. …

fix(service-proxy): oauth2-proxy ingress nginx annotations

---

.github/renovate.json

is true:
---
:question:
:question:
1. :question:
:question:

feat(deps): renovate pin digest in action

---

alerts/charts/Chart.yaml
alerts/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

chore(alerts): bump chart version

---

.github/workflows/ci-pr-build.yaml
.github/workflows/helm-release.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(ci): helm-release, ci-pr-build for cert-manager after cleanup

---

cert-manager/charts/Chart.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(charts): cert-manager add icon, keywords

---

logshipper/chart/Chart.yaml
logshipper/chart/values.yaml
logshipper/plugindefinition.yaml

This allows for optional opensearch shipping

fix(logshipper): make opensearch values optional

---

logs/charts/Chart.yaml
logs/charts/templates/_ceph-config.tpl
logs/charts/templates/_kvm-config.tpl
logs/charts/templates/logs-collector.yaml
logs/plugindefinition.yaml

revert changes implemented in #770

fix(logs): rm previous added config

---

Dockerfile.integration-test
thanos/charts/Chart.yaml
thanos/charts/templates/tests/test-thanos-config.yaml
thanos/charts/templates/tests/test-thanos.yaml
thanos/plugindefinition.yaml

closing https://github.com/cloudoperators/greenhouse-extensions/issues/757
adding health check request in integration test for thanos query grpc ingress hostname

feat(thanos) ingress hostname availability

---

Dockerfile.integration-test
thanos/charts/Chart.yaml
thanos/charts/templates/tests/test-thanos-config.yaml
thanos/plugindefinition.yaml

fix(testing) update grpcurl version

---

logs/charts/Chart.yaml
logs/charts/alerts/collector-alerts.yaml
logs/charts/alerts/operator-alerts.yaml
logs/plugindefinition.yaml

This fixes the missing link to the playbook when alerts are pushed to Slack.

fix(logs): update label for playbook

---

docs/catalog.md
opensearch/chart/Chart.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchactiongroups.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchclusters.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchcomponenttemplates.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchindextemplates.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchismpolicies.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchroles.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchtenants.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchuserrolebindings.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchusers.yaml
opensearch/plugindefinition.yaml

Align opensearch plugin crds to release namespace `opensearch-logs` 
None
Streamline with current OpenSearch setup

fix(opensearch): align crds release namespace

---

service-proxy/charts/1.0.0/service-proxy/Chart.yaml
service-proxy/charts/1.0.0/service-proxy/ci/test-values.yaml
service-proxy/charts/1.0.0/service-proxy/templates/oauth2-proxy-ingress.yaml
service-proxy/charts/1.0.0/service-proxy/values.yaml
service-proxy/plugindefinition.yaml

the auth redirect might fail for users with many assigned groups this increases the nginx proxy-buffer-size to 32k
is true:
---
:question:
:question:
Enter the issue numbers resolved by this pull request below, …

fix(service-proxy): add ingress buffer annotation

---

thanos/charts/Chart.yaml
thanos/charts/templates/tests/test-thanos-config.yaml
thanos/plugindefinition.yaml

integration test will fetch query sd-config and try to health probe each endpoint

test(thanos) endpoints availability

---

thanos/charts/Chart.yaml
thanos/charts/ci/test-values.yaml
thanos/charts/values.yaml
thanos/plugindefinition.yaml

- versioned tag for integration test
- clean up unused values

fix(thanos) integration-test-versionning

---

.github/workflows/license.yaml

is true:
---
github workflows are not triggered if a pipeline committed last this will ensure that changes commit by license action retrigger actions
:question:
1. :question: …

fix(actions): license action uses cloudoperator token

---

Makefile

missing /bin check for new binaries

fix(makefile) mkdir bin if not present

---

github-guard/charts/Chart.yaml
github-guard/charts/templates/manager-rbac.yaml
github-guard/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

feat(github-guard): bump to 1.1.0, fetch members from Team instead of TeamMembership

---

.github/renovate.json

closing #853 
"postUpdateOptions": ["helmUpdateSubChartArchives"]
to have renovate update subchart archives when udpating dependencies for helm

feat(renovate) helmUpdateSubChartArchives

---

github-guard/charts/Chart.yaml
github-guard/plugindefinition.yaml

resolves https://github.com/cloudoperators/repo-guard/issues/7

feat(repo-guard): bump to 1.2.0 - GithubUsername to GithubAccountLink switch

---

kubeconfig-generator/chart/Chart.yaml
kubeconfig-generator/chart/templates/deployment.yaml
kubeconfig-generator/plugindefinition.yaml

Make the `image.tag` value configurable for the `kubeconfig-generator`Plugin

feat(kubeconfig-generator): Make image tag configurable

---

.github/renovate.json

updating some failing renovate configs

fix(renovate) Dockerfile managers + perses plugindef

---

.github/workflows/helm-lint-test.yaml

Helm 3.18 as some issues. 
https://github.com/helm/helm/issues/30873
https://github.com/helm/helm/issues/30880
https://github.com/prometheus-community/helm-charts/issues/5648
---
:question:
:question:
1. :question:
:question:

chore(ci): Pin Helm Version

---

opensearch/README.md
opensearch/chart/Chart.yaml
opensearch/chart/values.yaml
opensearch/plugindefinition.yaml

Update kube-rbac-proxy used by OpenSearch Operator

chore(opensearch): update kube-rbac-proxy

---

.github/renovate.json
.github/workflows/sync-plugindefinition.yaml

bumping version in plugindefinition.yaml whenever renovate helmv3 manager updates helm dependencies

feat(renovate) plugindefinition manager

---

.github/configs/helm-lint-test.yaml
.github/workflows/helm-lint-test.yaml

see this workflow run as reference
https://github.com/cloudoperators/greenhouse-extensions/actions/runs/15215784964/job/42800864630

feat(automation) helm-test pod logs on failure

---

logs/charts/Chart.yaml
logs/charts/alerts/collector-alerts.yaml
logs/plugindefinition.yaml

Remove exporter label as it is not filled.

fix(logs): text logs missing

---

opensearch/chart/Chart.yaml
opensearch/chart/dashboards/opensearch-monitoring.json
opensearch/plugindefinition.yaml

fix(opensearch): fix perses dashboard

---

kustomization.yaml

is true:
---
`github-guard` was renamed to `repo-guard`

(fix): update github-guard to repo-guard

---

opensearch/chart/Chart.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchactiongroups.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchclusters.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchcomponenttemplates.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchindextemplates.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchismpolicies.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchroles.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchsnapshotpolicies.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchtenants.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchuserrolebindings.yaml
opensearch/chart/crds/opensearch.opster.io_opensearchusers.yaml
opensearch/plugindefinition.yaml

- Add update of CRDs which was missing in the latest version update to 2.8.0 https://github.com/cloudoperators/greenhouse-extensions/pull/1025
- Add new CRD: opensearchsnapshotpolicies

fix(opensearch): bring crds to latest version

---

service-proxy/charts/1.0.0/service-proxy/Chart.yaml
service-proxy/charts/1.0.0/service-proxy/values.yaml
service-proxy/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(service-proxy): set image version

---

kubeconfig-generator/chart/Chart.yaml
kubeconfig-generator/plugindefinition.yaml

Updates kubeconfig-generator to latest

chore(kubeconfig-generator): Update plugin

---

logs/charts/Chart.yaml
logs/charts/templates/_ceph-config.tpl
logs/plugindefinition.yaml

- introducing ceph-prysm container parsing
- consolidate label for `user_agent`

feat(logs): add ceph prysm parsing, consolidate user_agent labeling

---

service-proxy/charts/1.0.0/service-proxy/Chart.yaml
service-proxy/charts/1.0.0/service-proxy/values.yaml
service-proxy/plugindefinition.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(service-proxy): bump oauth2-proxy version

---

perses/README.md
perses/charts/Chart.yaml
perses/charts/values.yaml

Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>
is true:
---
:question:
:question:
1. :question: …

chore(perses): change provisioning interval to 3m

---

.github/workflows/helm-docs.yaml

Include write permissions for pull requests in the GitHub Actions configuration.

chore(ci): Add explicit permissions for pull requests in GitHub Actions

---

.github/workflows/license.yaml
.github/workflows/sync-plugindefinition.yaml
.github/workflows/trigger_hugo.yaml

This updates the usage of the cloudoperator user with the cloud operator bot app

chore(ci): replace PAT with APP token

---

.github/workflows/helm-docs.yaml
.github/workflows/helm-lint-test.yaml
.github/workflows/renovate-pr-sync.yaml
.github/workflows/sync-plugindefinition.yaml

- fixing permission for bumping charts on renvovate PRs
- new auto update comment for 10 mins showing status of workflows (since it can't be triggered on PR level by a bot)
- support version bumps in values.yaml (will bump Chart.yaml then plugindef.yaml)

feat(git-actions) sync plugindef fix + enhance

---

thanos/charts/Chart.yaml
thanos/charts/templates/blackbox-exporter/servicemonitor.yaml
thanos/plugindefinition.yaml

solves https://github.com/cloudoperators/greenhouse-extensions/issues/1078

fix(thanos) remove sap ref

---

perses/README.md
perses/charts/Chart.yaml
perses/charts/values.yaml
perses/plugindefinition.yaml

Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>
is true:
---
:question:
:question:
1. :question: …

refactor(perses): remove deprecated schemas configuration from values.yaml

---

opensearch/README.md
opensearch/chart/Chart.lock
opensearch/chart/Chart.yaml
opensearch/chart/values.yaml
opensearch/plugindefinition.yaml

feat(opensearch): upgrade to OpenSearch 3.0

---

heureka-scanner-k8s-assets/plugindefinition.yaml

Update link to helm chart repository for the heureka-scanner-k8s-assets plugin.

chore(heureka-scanner-k8s-assets): update chart repository

---

.github/workflows/trigger_hugo.yaml

is true:
---
:question:
:question:
1. :question:
:question:

fix(ci): update token for docs dispatch

---

logs/README.md
logs/charts/Chart.yaml
logs/charts/values.yaml
logs/plugindefinition.yaml

- Updating OTel Collector image to 0.133.0
- Updating OTel Operator image to v0.131.0

chore(logs): update collector and operator

---

heureka-scanner-k8s-assets/plugindefinition.yaml

Updates path to helm chart repository and bumps plugin version.

chore(heureka): update k8s-scanner chart repository

---

audit-logs/README.md
audit-logs/charts/Chart.yaml
audit-logs/charts/templates/_helpers.tpl
audit-logs/charts/templates/audit-logs-collector.yaml
audit-logs/charts/templates/pmon-filelog.yaml
audit-logs/charts/templates/smon.yaml
audit-logs/charts/values.yaml
audit-logs/plugindefinition.yaml
audit-logs/test-dependencies.yaml

- align with recent changes on Prometheus Labels
- add general receivers for containers and journal

refactor(audit-logs): lift to align with logs, add general receivers

---

perses/charts/Chart.yaml
perses/charts/templates/alerts.yaml
perses/plugindefinition.yaml

Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>
is true:
---
:question:
:question:
1. :question: …

fix(perses): Adopt to flux helm controller

---

logs/charts/Chart.yaml
logs/charts/templates/failover-config.tpl
logs/charts/templates/logs-collector.yaml
logs/plugindefinition.yaml

- Enables `sending_queue` for OpenSearch exporter to minimize data loss

feat(logs): enable sending queues for opensearch exporter

---

logs/plugindefinition.yaml

bump plugin version after last changes https://github.com/cloudoperators/greenhouse-extensions/pull/1202

chore(logs): bump plugin version
